unstable_features = true
binop_separator = "Back"
combine_control_expr = false
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
color = "Always"
max_width = 115