[package]
name = "arlox"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.152"
lazy_static = "1.4.0"

[dependencies.reqwest]
version = "0.11.14"
features = ["json", "cookies", "blocking"]

[dev-dependencies]
serde_json = "1.0.91"
tokio-test = "0.4.2"
dotenv = "0.15.0"